[profile.default]
src = 'contracts'
out = 'out'
script = 'scripts'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'forge-cache'

auto_detect_solc = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config